#ifndef __TSIRTOOLBOX_H__
#define __TSIRTOOLBOX_H__

#define TSIR_TOOLBOX_MAJOR_VERSION		2
#define TSIR_TOOLBOX_MINOR_VERSION		6
#define TSIR_TOOLBOX_SUBMINOR_VERSION	1

#endif // __TSIRTOOLBOX_H__